### ISSUE TITLE
Filtering with Phant for two columns of data

### ISSUE THREAD

**Issue by piettetech** [sparkfun/phant#135]
I have a data stream that has 9 values, I only want to have my data query return two.  I have tried to use the filtering in phant but I always get all 9 values.  Is that how it is suppose to work?

**Comment by git-hub-user** [comment]
I observe the same here. Filters do not seem to have any effect. Neither on our own instance of Phant, nor on public streams. for example, following the [Phant io documentation](http://phant.io/docs/output/http/), I would expect this to work:
https://data.sparkfun.com/streams/4Jr1NG5a80t7X06yqKmO?eq[outdoortemp]=71.6
but does show all data.
On the other hand, 
https://data.sparkfun.com/streams/4Jr1NG5a80t7X06yqKmO?gt[outdoortemp]=71.0
returns HTTP 502 Bad Gateway.

Very surprising that this basic functionality just doesn't work.

**Comment by git-hub-user** [comment]
OK, think I found it. Since the examples in the documentation, like https://data.sparkfun.com/output/xROQyrNEMoU6xQA2wro1?grep[humidity]=2952$, return 

> "no data has been pushed to this stream"

I looked for other public streams. But the home page of a stream does not looked at the query string. Change /streams/ to output and your filters will work. For example:
on public streams. for example, following the Phant io documentation, I would expect this to work:
https://data.sparkfun.com/output/4Jr1NG5a80t7X06yqKmO?eq[outdoortemp]=71.6
https://data.sparkfun.com/output/4Jr1NG5a80t7X06yqKmO?gt[outdoortemp]=71.0

You will get CSV by default, but can change this by specifying a format before the query string, like in: 
https://data.sparkfun.com/output/4Jr1NG5a80t7X06yqKmO.json?eq[outdoortemp]=71.6

The 502 Bad Gateway occurs frequently on the public server, but seems unrelated.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
