### ISSUE TITLE
Error 4 on my server, works fine on data.sparkfun

### ISSUE THREAD

**Issue by DanwithArduino** [sparkfun/phant#139]
Well, now that my nodejs/server problems have been fixed, I'm back to testing the arduino functions. Unfortunately, I'm getting "Error 4" 

I have inputted the IP from Digital Ocean/ the management page that i created there, including :8080, reset all of my keys to my new feed, etc, still no go. I am making a successful connection to my network - it is spitting out my IP address etc. When i reopen my original working code for sparkfun it all works fine. 

I am using the code as per the example/tutorial - not the library. 

Digital Ocean is configured for IpV6, not private networks

Im using the default "phant" npm install, not a custom. 

the server entry looks like: http://###.236.231.#98:8080

thanks for any help in trying to resolve this problem

**Comment by neophyte-savant** [comment]
So i just spent the last few hours, in addition to last night, trying some troubleshooting. 

I can access the HTTP side to create my streams etc, so i made my stream and edited the contents of my working code. 

The arduino-side  code im working off of is from the tutorial here: https://learn.sparkfun.com/tutorials/pushing-data-to-datasparkfuncom

I've tried changing the library for the SFE_CC3000 to use port 8080, and i've tried changing the "if ( !client.connect(server, 80) )" to 8080. I've tried having the http:// in the server entry, without it, with "/input", and every single iteration/combination of the above. 

For a verifcation that the problem is with the server connection, i changed my working code with data.sparkfun.com by mispelling the server - it resulted in the same error. 

I've experemented with cnaging the IP_ADDR_LEN for the length of the IP address in bytes from the default 4, to one above and one below. Still getting error 4, TCP. 

thanks for any help

**Comment by neophyte-savant** [comment]
So i changed my code from the server being a "char" to IPAddress, but its still failing. the following is my latest attempt to get this running 

[code]

#include <SPI.h>
#include <SFE_CC3000.h>
#include <SFE_CC3000_Client.h>
//#include <Progmem.h>

#define CC3000_INT      2   // Needs to be an interrupt pin (D2/D3)
#define CC3000_EN       7  // Can be any digital pin
#define CC3000_CS       10  // Preferred is pin 10 on Uno
#define IP_ADDR_LEN     4   // Length of IP address in bytes

// WiFi Constants //
////////////////////
char ap_ssid[] = "HOME-61B2";                  // SSID of network
char ap_password[] = "mypassword";          // Password of network
unsigned int ap_security = WLAN_SEC_WPA2; // Security of network
// ap_security can be any of: WLAN_SEC_UNSEC, WLAN_SEC_WEP,
//  WLAN_SEC_WPA, or WLAN_SEC_WPA2
unsigned int timeout = 45000;             // Milliseconds
IPAddress server = (###,236,2#1,#98);      // Remote host site 

// Initialize the CC3000 objects (shield and client):
SFE_CC3000 wifi = SFE_CC3000(CC3000_INT, CC3000_EN, CC3000_CS);
SFE_CC3000_Client client = SFE_CC3000_Client(wifi);

/////////////////
// Phant Stuff //
/////////////////
const String publicKey = "mypublickey";
const String privateKey = "myprivatekey";
const byte NUM_FIELDS = 4;
const String fieldNames[NUM_FIELDS] = {"inches", "name", "photo","switch"};
String fieldData[NUM_FIELDS];

//sensor info
const int photoPin=0;
int light;
const int sonicPin=4;
long sensor,distance;
const int switchPin = 10;
//string name line itmes
String name = "0000";
boolean newName1 = true;

//post timer info
int countdown = 0; //when countdown reaches 0 repost
unsigned long
sketchTime = 0L; //CPU miliseconds since last post
long previousMillis = 0;  
long interval = 10000;  

void setup()
{
 Serial.begin(115200);

 // Setup Input Pins:
 pinMode(sonicPin,INPUT);

 // Set Up WiFi:


 Serial.println(F("=========== Ready to Stream ==========="));
 Serial.println(F("Press the button (D3) to send an update"));
 Serial.println(F("Type your name, followed by '!' to update name"));
}
void loop()
{
// Read sensor
sensor=pulseIn(sonicPin,HIGH);
distance=sensor/147;
light=analogRead(photoPin);
time();
}

void time()
{
 unsigned long currentMillis = millis();
 
 if(currentMillis - previousMillis > interval) {
 // save the last time you blinked the LED
 previousMillis = currentMillis;
 setupWiFi();
 Serial.print(F("Inches: "));
 Serial.println(distance);
 Serial.print(F("Lumens"));
 Serial.println(light);
 dataPost();
 wifi.disconnect();

}
}
void dataPost()
{
 // Gather data:

 fieldData[0] = String(distance);
 fieldData[1] = String(digitalRead(switchPin));
 fieldData[2] = name;
 fieldData[3] = String (light);

 // Post data:
 Serial.println("Posting!");
// Make a TCP connection to remote host
if ( !client.connect(server, 8080) ) //removed ", 80"
{
 // Error: 4 - Could not make a TCP connection
 Serial.println(F("Error: 4"));
}

// Post the data! Request should look a little something like:
// GET /input/publicKey?private_key=privateKey&light=1024&switch=0&time=5201 HTTP/1.1\n
// Host: data.sparkfun.com\n
// Connection: close\n
// \n
client.print("GET /input/");
client.print(publicKey);
client.print("?private_key=");
client.print(privateKey);
for (int i=0; i<NUM_FIELDS; i++)
{
 client.print("&");
 client.print(fieldNames[i]);
 client.print("=");
 client.print(fieldData[i]);
}
client.println(" HTTP/1.1");
client.print("Host: ");
client.println(server);
client.println("Connection: close");
client.println();

while (client.connected())
{
 if ( client.available() )
 {
 char c = client.read();
 Serial.print(c);
 }
}
Serial.println();
}

void setupWiFi()
{
 ConnectionInfo connection_info;
 int i;

 // Initialize CC3000 (configure SPI communications)
 if ( wifi.init() )
 {
 Serial.println(F("CC3000 Ready!"));
 }
 else
 {
 // Error: 0 - Something went wrong during CC3000 init!
 Serial.println(F("Error: 0"));
 }

 // Connect using DHCP
 Serial.print(F("Connecting to: "));
 Serial.println(ap_ssid);
 if(!wifi.connect(ap_ssid, ap_security, ap_password, timeout))
 {
 // Error: 1 - Could not connect to AP
 Serial.println(F("Error: 1"));
 }

 // Gather connection details and print IP address
 if ( !wifi.getConnectionInfo(connection_info) )
 {
 // Error: 2 - Could not obtain connection details
 Serial.println(F("Error: 2"));
 }
 else
 {
 Serial.print(F("My IP: "));
 for (i = 0; i < IP_ADDR_LEN; i++)
 {
 Serial.print(connection_info.ip_address[i]);
 if ( i < IP_ADDR_LEN - 1 )
 {
 Serial.print(".");
 }
 }
 Serial.println();
 }
}
int freeRam () {
 extern int __heap_start, *__brkval;
 int v;
 return (int) &v - (__brkval == 0 ? (int) &__heap_start : (int) __brkval);
}
[/code[

**Comment by DanwithArduino** [comment]
ok i think i finally did it. (and in the process fried one SFE_3000 wifi board from accidentally shocking it with my finger - good thing i have two...)

I downloaded the repository from github for ver6.8. Then i went through and changed any reference i could possibly find to the port being 8080 to 80. I did not change the telnet port. I also changed the name in the package.json to "phantdeftest", as in phant default test. phantgittest might have made more sense, but whatever. 

I then followed the directions from github here: https://docs.npmjs.com/cli/publish to install it to the npm registry. 

installation to npm was done in W7 via node.js command prompt after i navigated to the local file position - all the way down to phant-master

One note for the noobs out there like me, the name must be all lower case. 

if anyone needs a port 80 phant, it can be found on npm at phantdeftest. 

Unfortunately, it seems to hang up an awful lot when posting. It'll start to type out "http" in the serial monitor then it locks up. I dont think that it was doing this when connected to the data.sparkfun server although it did occasionally lock up there as well but only after a few days. Im currently pushing data every 90seconds, when i was using the sparkfun server it was more like very 15minutes (which is where it will be when deployed). I wonder if Digital Ocean is too slow?

**Comment by toddtreece** [comment]
@DanwithArduino try @thcipriani's [recent vagrant addition](https://github.com/sparkfun/phant#vagrant) locally. you shouldn't need a separate package, and you can set the http port easily in the vagrant file.

**Comment by DanwithArduino** [comment]
Was able to get that sorted. I had seen the vagrant file but it seemed harder to setup than the method i used. Ultimately I'm sure I'm wrong. In any event, my problem now is that it seems to hangup - where it will do several successful posts, but then the serial monitor reports "posting!", the next line should be "http" etc etc, but it just hangs up typing out an "ht" or "htt" etc. The message from the terminal when this happens is above, so i dont think that it is a problem with the arduino in either my hardware or the libraries?

**Comment by toddtreece** [comment]
@DanwithArduino it's not really that you are wrong, but your forked package will be harder to maintain if updates are pushed to the upstream phant repo. try downloading a config using the tool found here: https://data.sparkfun.com/config that way you can benefit from updates without having to merge them in.

I think I see the bug in the phant http routing code that's throwing those errors. you can try to adjust your code to use a [HTTP POST](http://www.w3schools.com/tags/ref_httpmethods.asp) to avoid the routing bug.

**Comment by DanwithArduino** [comment]
Fair enough for the Vagrant - i didnt really understand it so i stuck with what i had a little bit of a grasp on. 

I tried using the config tool but the json that downloads with it reported version 1, instead of 6.8. This is why i downloaded the git as a zip and then went about changing the references in there (i think there are really only two that need to be changed, im assuming the "test" folder is not needed if you're not testing). My main fear now is that if i start posting the data and there is a good upgrade i might lose the data?

It looks like the arduino library on github uses POST, whereas the example uses GET. I'll load it up and see if it works better for me.

**Comment by toddtreece** [comment]
@DanwithArduino yep. the custom config package you configured and downloaded is at version 1, and phant v6.8 is listed as one of its dependencies.

it's a bit hard to explain because the phant ecosystem is really modular (probably to a fault currently), but phant itself is just a router between different phant modules. the configuration of phant with different modules is what gives you a working server, otherwise it has no inputs or outputs. if you take a look, the `index.js` in the config you downloaded from https://data.sparkfun.com/config looks a lot like the default server config in `.bin/serve` of the main phant repo. they are both server configs, and `.bin/serve` was included in the package so people could start up a server without writing a config and test it out.

i'm not sure if that info helps at all, but i'm glad you got it sorted.
