### ISSUE TITLE
Where are stored the datas in a local installation?

### ISSUE THREAD

**Issue by couilloux** [sparkfun/phant#211]
Hi,

Im using a local install of phant on my own server and everything is working well.

I would like to backup my data but I cant find where the data are stored? sqlite? any other database type? 

Does someone can help me ?

Thanks

Julien

**Comment by ebeeche** [comment]
Phant stores stream data and its corresponding headers in two different files (for each stream) their location is:

```
phant-dir/phant_streams/XXXX/YYYYYYYY/headers.csv
phant-dir/phant_streams/XXXX/YYYYYYYY/stream.csv
```

Where `XXXX` is a 4 positions hex number and `YYYYYYYY` is a 28 positions hex number .  
As the .csv extension suggests, data inside those files is stored in comma separated values.

To my knowledge, both hex numbers are assigned arbitrarily by Phant.

Hope this helps.  And if it does, **please close the issue** because this is actually not an issue/bug.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
