### ISSUE TITLE
Consider MQTT input

### ISSUE THREAD

**Issue by jsilence** [sparkfun/phant#55]
MQTT (http://mqtt.org) seems to be an appropriate protocol for data transfer from small embedded machines. Client libraries for a wide range of languages are available. The broker of choice currently seems to be Mosquitto, but other MQ brokers also understand the mqtt protocol.
Would be nice, if phant could subscribe to a mqtt topic and collect data from there.

**Comment by bbhoss** [comment]
I'm trying to publish to "input/PUBLIC/PRIVATE" to no avail. The server just immediately closes the connection without cause. Can someone confirm this still works?

Thanks

**Comment by hollie** [comment]
I'm using the MQTT interface to receive values from a datastream on data.sparkfun.com and it works well.

One question: would be possible to set the 'retained' flag to data that is posted to the MQTT broker? This way a new client gets an update of the last received value from the broker upon connecting. Otherwise the client needs to wait for a new value to be posted to the broker before it receives its first value. If there are only a few values posted per day then the client is in the blue about the status of the data source for quite an extended time. The retained flag solves this. See [here](http://www.hivemq.com/mqtt-essentials-part-8-retained-messages/) for some more details on this.

Regards,
 Lieven.

**Comment by q2dg** [comment]
Last suggestion is interesting.
On the other hand: "I'm going to close this issue, but I'll post once SSL is enabled."...isn't it still?
Thanks!

**Comment by erniberni** [comment]
I just tried to connect to my stream at data.sparkfun.com with a mqtt client and failed
broker: data.sparkfun.com
port:1883
(no connection to broker)
What I'm doing wrong ?

**Comment by erniberni** [comment]
After some trials with Chromium MQTT Client and also Arduino I found the MQTT broker on data.sparkfun.com very unreliable. Most times the connection breaks after a while and not all messages (changes on the channel) are submitted to the subscribed client. 
The same test arrangement is running with broker.hivemq.com very stable.

**Comment by q2dg** [comment]
Latest commit is from 3 Nov 2015. 
Mmm...mmmm

**Comment by erniberni** [comment]
I know, but the service is working. Any alternative?
